package rules.ticket

import com.plugin.drools.Customer
import com.plugin.drools.Ticket

rule "New Ticket"
	salience 10
	when
		customer : Customer()
		ticket : Ticket(customer == customer, status == "New")
	then
		System.out.println("Start processing Ticket # " + ticket.getId() + " with customer " + customer.getName());
end

rule "Bronze Priority"
	when
		customer : Customer(subscription == "Bronze")
		ticket : Ticket(customer == customer, status == "New")
	then
		System.out.println("Firing rule Bronze Priority for Ticket # " + ticket.getId());
		modify(ticket) { setStatus("Pending") };
end
  
rule "Silver Priority"
	when
		customer : Customer(subscription == "Silver")
		ticket : Ticket(customer == customer, status == "New")
	then
		System.out.println("Firing rule Silver Priority for Ticket # " + ticket.getId());
		modify(ticket) { setStatus("Escalate") };
end

rule "Gold Priority"
	when
		customer : Customer(subscription == "Gold")
		ticket : Ticket(customer == customer, status == "New")
	then
		System.out.println("Firing rule Gold Priority for Ticket # " + ticket.getId());
		modify(ticket) { setStatus("Escalate") };
end

rule "Special Discount"
	when
		customer : Customer(subscription == "Gold")
		ticket : Ticket(customer == customer, status == "Escalate")
	then
		System.out.println("Firing rule Special Discount for Ticket # " + ticket.getId());
		customer.setDiscount(5);
end
